# Amira Project 601
# AmiraZIBEdition
# Generated by AmiraZIBEdition 6.0.1

# This script has three template arguments (they are in the body of the script):
# <INPUT_SURFACE_FILE_NAME>: the file name (with path) of the input surface (the one to be remeshed)
# <OUTPUT_SURFACE_FILE_NAME>: the name (with path) of the remeshed surface (it will be saved in OBJ format)
# <OUTPUT_MESH_SIZE_PERCENT>: the size of the output mesh as percentage of the input mesh size

remove -all

set hideNewModules 0
[ load <INPUT_SURFACE_FILE_NAME> ] setLabel "input_surface"
"input_surface" setIconPosition 37 98
"input_surface" master disconnect
"input_surface" fire
"input_surface" LevelOfDetail setMinMax -1 -1
"input_surface" LevelOfDetail setButtons 1
"input_surface" LevelOfDetail setEditButton 1
"input_surface" LevelOfDetail setIncrement 1
"input_surface" LevelOfDetail setValue -1
"input_surface" LevelOfDetail setSubMinMax -1 -1
"input_surface" setTransform 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1
"input_surface" fire
"input_surface" setViewerMask 16383

set hideNewModules 0
create HxRemeshSurface "surface_remesher"
"surface_remesher" setIconPosition 210 161
"surface_remesher" setVar "CustomHelp" {HxRemeshSurface}
"surface_remesher" data connect "input_surface"
"surface_remesher" fire
"surface_remesher" densityField disconnect
"surface_remesher" fire
"surface_remesher" minEdgeLength disconnect
"surface_remesher" fire
"surface_remesher" advancedOptions setValue 0 0
"surface_remesher" advancedOptions setToggleVisible 0 1
"surface_remesher" objective setIndex 0 0
"surface_remesher" triangleArea setMinMax 0 -16777216 16777216
"surface_remesher" triangleArea setValue 0 5
"surface_remesher" triangleArea setMinMax 1 -16777216 16777216
"surface_remesher" triangleArea setValue 1 3
"surface_remesher" triangleArea setMinMax 2 -16777216 16777216
"surface_remesher" triangleArea setValue 2 3
"surface_remesher" vertexValence setMinMax 0 -16777216 16777216
"surface_remesher" vertexValence setValue 0 1
"surface_remesher" triangleQuality setMinMax 0 -16777216 16777216
"surface_remesher" triangleQuality setValue 0 10
"surface_remesher" lloydRelaxation setMinMax 0 -16777216 16777216
"surface_remesher" lloydRelaxation setValue 0 40
"surface_remesher" desiredSize setValue 2 <OUTPUT_MESH_SIZE_PERCENT>
"surface_remesher" errorThresholds setMinMax 0 -3.40282346638529e+38 3.40282346638529e+38
"surface_remesher" errorThresholds setValue 0 0
"surface_remesher" errorThresholds setMinMax 1 -3.40282346638529e+38 3.40282346638529e+38
"surface_remesher" errorThresholds setValue 1 0
"surface_remesher" densityContrast setMinMax 0 -3.40282346638529e+38 3.40282346638529e+38
"surface_remesher" densityContrast setValue 0 1
"surface_remesher" densityRange setMinMax 0 -3.40282346638529e+38 3.40282346638529e+38
"surface_remesher" densityRange setValue 0 0.69867616891861
"surface_remesher" densityRange setMinMax 1 -3.40282346638529e+38 3.40282346638529e+38
"surface_remesher" densityRange setValue 1 1302.4169921875
"surface_remesher" interpolateOrigSurface setValue 1
"surface_remesher" remeshOptions1 setValue 0 0
"surface_remesher" remeshOptions1 setToggleVisible 0 1
"surface_remesher" remeshOptions1 setValue 1 1
"surface_remesher" remeshOptions1 setToggleVisible 1 1
"surface_remesher" surfacePathOptions setValue 0 0
"surface_remesher" surfacePathOptions setToggleVisible 0 1
"surface_remesher" surfacePathOptions setValue 1 1
"surface_remesher" surfacePathOptions setToggleVisible 1 1
"surface_remesher" remeshOptions2 setValue 0
"surface_remesher" contourLayers setMinMax 0 -16777216 16777216
"surface_remesher" contourLayers setValue 0 4
"surface_remesher" SurfacePathSet1 disconnect
"surface_remesher" fire
"surface_remesher" applyTransformToResult 1
"surface_remesher" fire
"surface_remesher" setViewerMask 16383
"surface_remesher" setPickable 1

set hideNewModules 0
[ {surface_remesher} create result ] setLabel "remeshed_surface"
"remeshed_surface" setIconPosition 20 197
"remeshed_surface" master connect "surface_remesher" "result"
"remeshed_surface" fire
"remeshed_surface" LevelOfDetail setMinMax -1 -1
"remeshed_surface" LevelOfDetail setButtons 1
"remeshed_surface" LevelOfDetail setEditButton 1
"remeshed_surface" LevelOfDetail setIncrement 1
"remeshed_surface" LevelOfDetail setValue -1
"remeshed_surface" LevelOfDetail setSubMinMax -1 -1
"remeshed_surface" setTransform 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1
"remeshed_surface" fire
"remeshed_surface" setViewerMask 16383

"remeshed_surface" exportData "Wavefront" "<OUTPUT_SURFACE_FILE_NAME>"
exit
